name: simple_auth
description: Simple Auth is the simplest way to authenticate your users/apis.
version: 2.0.10
author: James Clancey <james.clancey@gmail.com>
homepage: https://github.com/clancey/simple_auth

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.9.1
  http: ^1.0.0
  crypto: ^3.0.3

#dev_dependencies:
#  test: ^1.15.7
